apiVersion: v1
kind: Pod
metadata:
  name: pinger-priv
  labels:
    app: pinger
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - /bin/sh
    - -c
    - |
      while true; do
        ping -c 1 8.8.8.8;
        sleep 2;
      done
    securityContext:
      privileged: true
  restartPolicy: Never
